version: '3.8'

services:
  web:
    build: .
    ports:
      - "${WEB_PORT:-8001}:8001"
    depends_on:
      citus-coordinator:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - messages_network

  citus-coordinator:
    image: citusdata/citus:latest
    container_name: citus-coordinator
    ports:
      - "5442:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-messages_db}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../.db_data/citus_coordinator_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - messages_network

  citus-worker1:
    image: citusdata/citus:latest
    container_name: citus-worker1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-messages_db}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../.db_data/citus_worker1_data:/var/lib/postgresql/data
    depends_on:
      - citus-coordinator
    networks:
      - messages_network

  citus-worker2:
    image: citusdata/citus:latest
    container_name: citus-worker2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-messages_db}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../.db_data/citus_worker2_data:/var/lib/postgresql/data
    depends_on:
      - citus-coordinator
    networks:
      - messages_network

  tarantool:
    image: tarantool/tarantool:latest
    container_name: tarantool
    ports:
      - "3301:3301"
    environment:
      TARANTOOL_USER_NAME: ${TARANTOOL_USER:-admin}
      TARANTOOL_USER_PASSWORD: ${TARANTOOL_PASSWORD:-admin}
    volumes:
      - ./tarantool/init.lua:/opt/tarantool/init.lua
      - ../.db_data/tarantool_data:/var/lib/tarantool
    command: tarantool /opt/tarantool/init.lua
    networks:
      - messages_network

volumes:
  citus_coordinator_data:
  citus_worker1_data:
  citus_worker2_data:
  tarantool_data:


networks:
  messages_network:
    name: service_networks
    external: true
